// This file is generated by `mise run generate-api-types`. Do not edit.
export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddChannelAgentsRequest: {
            agent_member_ids: string[];
        };
        AgentCreateApprovalPayload: {
            /** @enum {string} */
            access_level: "member";
            /** Format: uuid */
            computer_id: string;
            /** @enum {string} */
            driver_kind: "codex" | "builtin";
            name: string;
            permissions: string[];
            role_text: string;
        };
        AgentResponse: {
            /** @enum {string} */
            access_level: "member" | "admin";
            /** @enum {string} */
            activity_status: "idle" | "queued" | "starting" | "running" | "stopping" | "unreachable" | "suspended" | "error";
            attention_config: components["schemas"]["AttentionConfig"];
            /** Format: uuid */
            computer_id: string;
            /** Format: date-time */
            created_at: string;
            /** @enum {string} */
            desired_lifecycle: "active" | "suspended" | "retired";
            /** @enum {string} */
            driver_kind: "codex" | "builtin";
            handle: string;
            last_error_code?: string | null;
            /** Format: uuid */
            member_id: string;
            memory_files: components["schemas"]["MemoryFileResponse"][];
            name: string;
            /** @enum {string} */
            provision_status: "provisioning" | "ready" | "error";
            /** Format: date-time */
            retired_at?: string | null;
            /** Format: int64 */
            role_revision: number;
            role_text: string;
            /** Format: uuid */
            space_id: string;
            /** Format: date-time */
            updated_at: string;
        };
        ApprovalResponse: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            payload: components["schemas"]["AgentCreateApprovalPayload"];
            /** Format: uuid */
            requested_by_member_id: string;
            requester_name: string;
            /** Format: date-time */
            resolved_at?: string | null;
            /** Format: uuid */
            resolved_by_member_id?: string | null;
            /** Format: uuid */
            space_id: string;
            /** @enum {string} */
            status: "pending" | "approved" | "rejected" | "canceled";
            /** @enum {string} */
            type: "agent.create";
        };
        AttachmentResponse: {
            /** Format: date-time */
            created_at: string;
            download_path?: string | null;
            /** Format: uuid */
            id: string;
            media_type: string;
            original_name: string;
            sha256?: string | null;
            /** Format: int64 */
            size?: number | null;
            /** Format: uuid */
            space_id: string;
            /** @enum {string} */
            status: "uploading" | "ready" | "deleted";
            upload_path?: string | null;
            /** Format: uuid */
            uploader_member_id: string;
        };
        AttentionConfig: {
            /** Format: int32 */
            ambient_debounce_seconds: number;
            ambient_enabled: boolean;
            /** Format: int32 */
            ambient_max_wait_seconds: number;
            /** @enum {boolean} */
            dm_immediate: true;
            /** Format: int32 */
            max_retry_count: number;
            /** @enum {boolean} */
            mention_immediate: true;
        };
        ChannelListResponse: {
            can_create: boolean;
            channels: components["schemas"]["ChannelResponse"][];
        };
        ChannelMembersResponse: {
            can_manage: boolean;
            members: components["schemas"]["MemberResponse"][];
        };
        ChannelResponse: {
            /** Format: date-time */
            archived_at?: string | null;
            /** Format: uuid */
            created_by_member_id: string;
            /** Format: uuid */
            id: string;
            joined: boolean;
            /** @enum {string} */
            kind: "public" | "private";
            name: string;
            slug: string;
            /** Format: uuid */
            space_id: string;
            topic?: string | null;
        };
        CompleteUploadRequest: {
            sha256: string;
            /** Format: int64 */
            size: number;
        };
        ComputerResponse: {
            /** Format: date-time */
            created_at: string;
            daemon_version: string;
            hostname: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            last_seen_at?: string | null;
            name: string;
            /** @enum {string} */
            os: "macos" | "linux";
            /** Format: uuid */
            space_id: string;
            /** @enum {string} */
            status: "online" | "offline" | "revoked";
        };
        ConfirmPairingRequest: {
            code: string;
            name: string;
            /** Format: uuid */
            space_id: string;
        };
        CreateAgentRequest: {
            /** @enum {string} */
            access_level: "member" | "admin";
            /** Format: uuid */
            computer_id: string;
            /** @enum {string} */
            driver_kind: "codex" | "builtin";
            handle?: string | null;
            name: string;
            role_text: string;
        };
        CreateChannelRequest: {
            agent_member_ids: string[];
            /** @enum {string} */
            kind: "public" | "private";
            name: string;
            slug: string;
            topic?: string | null;
        };
        CreateDirectMessageRequest: {
            /** Format: uuid */
            member_id: string;
        };
        CreateInvitationRequest: {
            email: string;
            invite_token: string;
        };
        CreateMessageRequest: {
            attachment_ids?: string[];
            body_markdown: string;
            mentions?: string[];
        };
        CreateSpaceRequest: {
            accent: string;
            name: string;
            slug: string;
        };
        CreateThreadMessageRequest: {
            attachment_ids?: string[];
            body_markdown: string;
            mentions?: string[];
            /** Format: uuid */
            reply_to_message_id?: string | null;
        };
        CreateThreadRequest: {
            /** Format: uuid */
            root_message_id: string;
        };
        CreateUploadRequest: {
            media_type: string;
            original_name: string;
            /** Format: uuid */
            space_id: string;
        };
        DeferRequest: {
            /** Format: date-time */
            until: string;
        };
        DirectMessageResponse: {
            /** Format: uuid */
            channel_id: string;
            /** Format: date-time */
            created_at: string;
            other_member: components["schemas"]["MemberResponse"];
            /** Format: uuid */
            space_id: string;
        };
        ErrorBody: {
            code: string;
            details?: unknown;
            message: string;
        };
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        InboxItemResponse: {
            /** Format: uuid */
            approval_id?: string | null;
            /** Format: date-time */
            available_at: string;
            /** Format: uuid */
            channel_id?: string | null;
            channel_slug?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "direct" | "mention" | "reply" | "thread_activity" | "channel_activity" | "approval" | "system";
            /** Format: uuid */
            member_id: string;
            /** Format: uuid */
            message_id?: string | null;
            /** @enum {string} */
            priority: "hard" | "ambient";
            sender_display_name?: string | null;
            /** Format: uuid */
            sender_member_id?: string | null;
            /** @enum {string} */
            status: "pending" | "deferred" | "handled";
            summary?: string | null;
            /** Format: int64 */
            thread_id?: number | null;
        };
        InvitationResponse: {
            email: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            space_id: string;
            space_name: string;
            space_slug: string;
        };
        LifecycleAction: {
            /** @enum {string} */
            action: "suspend";
            mode: components["schemas"]["SuspendMode"];
        } | {
            /** @enum {string} */
            action: "resume";
        } | {
            /** @enum {string} */
            action: "retry";
        } | {
            /** @enum {string} */
            action: "retire";
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        LoginResponse: {
            user: components["schemas"]["UserResponse"];
        };
        MemberResponse: {
            /** @enum {string} */
            access_level: "owner" | "admin" | "member";
            display_name: string;
            handle: string;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "human" | "agent";
            permissions: string[];
        };
        MemoryContentResponse: {
            content: string;
            path: string;
            sha256: string;
            /** Format: int64 */
            size: number;
            /** Format: date-time */
            updated_at: string;
        };
        MemoryFileResponse: {
            path: string;
            sha256: string;
            /** Format: int64 */
            size: number;
            /** Format: date-time */
            updated_at: string;
        };
        MessageAuthor: {
            display_name: string;
            handle: string;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "human" | "agent";
        };
        MessagePageResponse: {
            /** Format: uuid */
            channel_id: string;
            has_more_after: boolean;
            has_more_before: boolean;
            messages: components["schemas"]["MessageResponse"][];
            /** Format: int64 */
            snapshot_channel_seq: number;
        };
        MessageResponse: {
            attachments: components["schemas"]["AttachmentResponse"][];
            author: components["schemas"]["MessageAuthor"];
            body_markdown: string;
            /** Format: uuid */
            channel_id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            deleted_at?: string | null;
            /** Format: date-time */
            edited_at?: string | null;
            /** Format: uuid */
            id: string;
            mentions: string[];
            /** Format: int64 */
            reply_count: number;
            /** Format: int64 */
            seq: number;
            task?: null | components["schemas"]["MessageTaskSummary"];
            /** Format: int64 */
            thread_id?: number | null;
        };
        MessageTaskSummary: {
            /** Format: uuid */
            assigned_agent_member_id?: string | null;
            assignee_name?: string | null;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "open" | "in_progress" | "done" | "canceled";
            title: string;
        };
        PairingDetailsResponse: {
            daemon_version: string;
            /** Format: date-time */
            expires_at: string;
            hostname: string;
            os: string;
            /** Format: uuid */
            pairing_id: string;
            /** @enum {string} */
            status: "pending" | "confirmed" | "expired";
            token_fingerprint: string;
        };
        ReadMemoryRequest: {
            path: string;
        };
        RegisterRequest: {
            display_name: string;
            email: string;
            password: string;
        };
        RegisterResponse: {
            next: string;
            user: components["schemas"]["UserResponse"];
        };
        SpaceResponse: {
            accent: string;
            /** Format: uuid */
            current_member_id: string;
            /** Format: uuid */
            general_channel_id: string;
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            owner_member_id: string;
            slug: string;
        };
        /** @enum {string} */
        SuspendMode: "stop_after_current" | "cancel_now";
        TaskResponse: {
            /** Format: uuid */
            assigned_agent_member_id?: string | null;
            assignee_name?: string | null;
            /** Format: uuid */
            channel_id: string;
            channel_slug: string;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            created_by_member_id: string;
            creator_name: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            source_message_id: string;
            /** Format: int64 */
            source_seq: number;
            /** Format: uuid */
            space_id: string;
            /** @enum {string} */
            status: "open" | "in_progress" | "done" | "canceled";
            title: string;
            /** Format: date-time */
            updated_at: string;
        };
        ThreadReadResponse: {
            /** Format: uuid */
            channel_id: string;
            is_following: boolean;
            replies: components["schemas"]["MessageResponse"][];
            root: components["schemas"]["MessageResponse"];
            /** Format: int64 */
            snapshot_channel_seq: number;
            /** Format: int64 */
            thread_id: number;
        };
        ThreadResponse: {
            /** Format: uuid */
            channel_id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            created_by_member_id: string;
            /** Format: uuid */
            root_message_id: string;
            /** Format: int64 */
            thread_id: number;
        };
        ThreadSubscriptionResponse: {
            /** Format: uuid */
            channel_id: string;
            is_following: boolean;
            /** Format: int64 */
            thread_id: number;
        };
        UpdateAgentRequest: {
            attention_config?: null | components["schemas"]["AttentionConfig"];
            lifecycle?: null | components["schemas"]["LifecycleAction"];
            role_text?: string | null;
        };
        UpdateMemberRequest: {
            access_level?: string | null;
            permissions?: string[] | null;
        };
        UserResponse: {
            display_name: string;
            email: string;
            /** Format: uuid */
            id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;

export type AddChannelAgentsInput = components["schemas"]["AddChannelAgentsRequest"];
export type Agent = components["schemas"]["AgentResponse"];
export type AgentMemoryContent = components["schemas"]["MemoryContentResponse"];
export type AgentMemoryFile = components["schemas"]["MemoryFileResponse"];
export type Approval = components["schemas"]["ApprovalResponse"];
export type Attachment = components["schemas"]["AttachmentResponse"];
export type AttentionConfig = components["schemas"]["AttentionConfig"];
export type Channel = components["schemas"]["ChannelResponse"];
export type ChannelList = components["schemas"]["ChannelListResponse"];
export type ChannelMembers = components["schemas"]["ChannelMembersResponse"];
export type CompleteUploadInput = components["schemas"]["CompleteUploadRequest"];
export type Computer = components["schemas"]["ComputerResponse"];
export type ConfirmPairingInput = components["schemas"]["ConfirmPairingRequest"];
export type CreateAgentInput = components["schemas"]["CreateAgentRequest"];
export type CreateChannelInput = components["schemas"]["CreateChannelRequest"];
export type CreateDirectMessageInput = components["schemas"]["CreateDirectMessageRequest"];
export type CreateInvitationInput = components["schemas"]["CreateInvitationRequest"];
export type CreateMessageInput = components["schemas"]["CreateMessageRequest"];
export type CreateSpaceInput = components["schemas"]["CreateSpaceRequest"];
export type CreateThreadInput = components["schemas"]["CreateThreadRequest"];
export type CreateThreadReplyInput = components["schemas"]["CreateThreadMessageRequest"];
export type CreateUploadInput = components["schemas"]["CreateUploadRequest"];
export type DeferInboxInput = components["schemas"]["DeferRequest"];
export type DirectMessage = components["schemas"]["DirectMessageResponse"];
export type ErrorEnvelope = components["schemas"]["ErrorEnvelope"];
export type InboxItem = components["schemas"]["InboxItemResponse"];
export type Invitation = components["schemas"]["InvitationResponse"];
export type LoginInput = components["schemas"]["LoginRequest"];
export type LoginResponse = components["schemas"]["LoginResponse"];
export type Member = components["schemas"]["MemberResponse"];
export type Message = components["schemas"]["MessageResponse"];
export type MessageAuthor = components["schemas"]["MessageAuthor"];
export type MessagePage = components["schemas"]["MessagePageResponse"];
export type MessageTaskSummary = components["schemas"]["MessageTaskSummary"];
export type PairingDetails = components["schemas"]["PairingDetailsResponse"];
export type ReadAgentMemoryInput = components["schemas"]["ReadMemoryRequest"];
export type RegisterInput = components["schemas"]["RegisterRequest"];
export type RegisterResponse = components["schemas"]["RegisterResponse"];
export type Space = components["schemas"]["SpaceResponse"];
export type Task = components["schemas"]["TaskResponse"];
export type Thread = components["schemas"]["ThreadResponse"];
export type ThreadRead = components["schemas"]["ThreadReadResponse"];
export type ThreadSubscription = components["schemas"]["ThreadSubscriptionResponse"];
export type UpdateAgentInput = components["schemas"]["UpdateAgentRequest"];
export type UpdateMemberInput = components["schemas"]["UpdateMemberRequest"];
export type User = components["schemas"]["UserResponse"];
