// This file is generated by `mise run generate-api-types`. Do not edit.
export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        AccessLevel: "owner" | "admin" | "member";
        ActionAgentResponse: {
            available: boolean;
            lifecycle: components["schemas"]["AgentLifecycle"];
            /** Format: uuid */
            member_id: string;
            name: string;
        };
        ActionChannelResponse: {
            available: boolean;
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
        };
        AddChannelAgentsRequest: {
            agent_member_ids: string[];
        };
        /** @enum {string} */
        AgentAccessLevel: "member" | "admin";
        AgentActivityResponse: {
            kind: string;
            label: string;
            status: components["schemas"]["AgentActivityStatus"];
        };
        /**
         * @description What the Agent is doing. Independent of whether its Computer is reachable: an Agent can be
         *     `working` while `computer_reachable` is false, which is the honest description of a Run in progress
         *     on a Computer we cannot currently reach.
         * @enum {string}
         */
        AgentActivityStatus: "idle" | "dispatched" | "working" | "suspended" | "error";
        /** @enum {string} */
        AgentLifecycle: "active" | "suspended" | "retired";
        AgentResponse: {
            access_level: components["schemas"]["AgentAccessLevel"];
            activity?: null | components["schemas"]["AgentActivityResponse"];
            activity_status: components["schemas"]["AgentActivityStatus"];
            attention_config: components["schemas"]["AttentionConfig"];
            /** Format: uuid */
            computer_id?: string | null;
            /**
             * @description Whether the Computer hosting this Agent is currently connected. Reported separately from
             *     `activity_status` so a Run in progress is not relabelled as unreachable.
             */
            computer_reachable: boolean;
            created_at: string;
            desired_lifecycle: components["schemas"]["AgentLifecycle"];
            driver_kind: components["schemas"]["DriverKind"];
            last_error_code?: string | null;
            /** Format: uuid */
            member_id: string;
            memory_files: components["schemas"]["MemoryFileResponse"][];
            name: string;
            provision_status: components["schemas"]["ProvisionStatus"];
            retired_at?: string | null;
            /** Format: int64 */
            role_revision: number;
            role_text: string;
            /** Format: uuid */
            space_id: string;
            updated_at: string;
        };
        AgentRuntimeResponse: {
            another_item_waiting: boolean;
            current_run?: null | components["schemas"]["RunResponse"];
            current_task?: null | components["schemas"]["TaskResponse"];
            focus?: null | components["schemas"]["ThreadReferenceResponse"];
            session_continuity: components["schemas"]["SessionContinuityResponse"];
        };
        AttachmentResponse: {
            created_at: string;
            download_path?: string | null;
            /** Format: uuid */
            id: string;
            media_type: string;
            original_name: string;
            sha256?: string | null;
            /** Format: int64 */
            size?: number | null;
            /** Format: uuid */
            space_id: string;
            status: components["schemas"]["AttachmentStatus"];
            upload_path?: string | null;
            /** Format: uuid */
            uploader_member_id: string;
        };
        /** @enum {string} */
        AttachmentStatus: "uploading" | "ready" | "deleted";
        AttentionConfig: {
            /** Format: int32 */
            ambient_debounce_seconds: number;
            ambient_enabled: boolean;
            /** Format: int32 */
            ambient_max_wait_seconds: number;
            dm_immediate: boolean;
            /** Format: int32 */
            max_retry_count: number;
            mention_immediate: boolean;
        };
        AttentionFailureResponse: {
            /** Format: uuid */
            agent_member_id: string;
            error_code: string;
            retrying: boolean;
        };
        /** @enum {string} */
        ChannelKind: "public" | "private";
        ChannelListResponse: {
            can_create: boolean;
            channels: components["schemas"]["ChannelResponse"][];
        };
        ChannelMembersResponse: {
            can_manage: boolean;
            members: components["schemas"]["MemberResponse"][];
        };
        ChannelResponse: {
            archived_at?: string | null;
            /** Format: uuid */
            created_by_member_id: string;
            /** Format: uuid */
            id: string;
            joined: boolean;
            kind: components["schemas"]["ChannelKind"];
            name: string;
            slug: string;
            /** Format: uuid */
            space_id: string;
            topic?: string | null;
        };
        /** @enum {string} */
        CloseReason: "invalid" | "duplicate" | "not_needed" | "obsolete" | "other";
        CloseTaskRequest: {
            note?: string | null;
            reason: components["schemas"]["CloseReason"];
        };
        CompleteTaskRequest: {
            result_markdown: string;
            /** Format: uuid */
            result_thread_id: string;
        };
        CompleteUploadRequest: {
            sha256: string;
            /** Format: int64 */
            size: number;
        };
        /** @enum {string} */
        ComputerOs: "macos" | "linux";
        ComputerResponse: {
            created_at: string;
            daemon_version: string;
            hostname: string;
            /** Format: uuid */
            id: string;
            last_seen_at?: string | null;
            name: string;
            os: components["schemas"]["ComputerOs"];
            /** Format: uuid */
            space_id: string;
            status: components["schemas"]["ComputerStatus"];
        };
        /** @enum {string} */
        ComputerStatus: "online" | "offline" | "revoked";
        ConfirmPairingRequest: {
            code: string;
            name: string;
            /** Format: uuid */
            space_id: string;
        };
        CreateAgentRequest: {
            access_level: components["schemas"]["AgentAccessLevel"];
            /** Format: uuid */
            computer_id: string;
            driver_kind: components["schemas"]["DriverKind"];
            name: string;
            role_text: string;
        };
        CreateChannelRequest: {
            agent_member_ids: string[];
            kind: components["schemas"]["ChannelKind"];
            name: string;
            slug: string;
            topic?: string | null;
        };
        CreateDirectMessageRequest: {
            /** Format: uuid */
            member_id: string;
        };
        CreateInvitationRequest: {
            email: string;
        };
        CreateMessageRequest: {
            attachment_ids: string[];
            body_markdown: string;
            mention_all: boolean;
            mentions: string[];
        };
        CreateSpaceRequest: {
            accent: string;
            name: string;
            slug: string;
        };
        CreateTaskRequest: {
            /** Format: uuid */
            assignee_agent_member_id?: string | null;
            title?: string | null;
        };
        CreateThreadMessageRequest: {
            attachment_ids: string[];
            body_markdown: string;
            mention_all: boolean;
            mentions: string[];
            /** Format: uuid */
            reply_to_message_id?: string | null;
        };
        CreateUploadRequest: {
            media_type: string;
            original_name: string;
            /** Format: uuid */
            space_id: string;
        };
        CreatedInvitationResponse: {
            accepted_at?: string | null;
            /** Format: uuid */
            accepted_by_member_id?: string | null;
            email: string;
            expires_at: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            space_id: string;
            space_name: string;
            space_slug: string;
            token?: string | null;
        };
        DirectMessageResponse: {
            /** Format: uuid */
            channel_id: string;
            created_at: string;
            other_member: components["schemas"]["MemberResponse"];
            /** Format: uuid */
            space_id: string;
        };
        /** @enum {string} */
        DriverKind: "codex" | "builtin";
        ErrorBody: {
            code: string;
            message: string;
            retryable: boolean;
        };
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        InboxItemResponse: {
            available_at: string;
            /** Format: uuid */
            channel_id?: string | null;
            channel_slug?: string | null;
            created_at: string;
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["InboxKind"];
            /** Format: uuid */
            member_id: string;
            /** Format: uuid */
            message_id?: string | null;
            /** @description A bounded preview of the source Message body. Full content is read through the Message API. */
            message_preview?: string | null;
            priority: components["schemas"]["InboxPriority"];
            /**
             * Format: int32
             * @description Times a governor returned this Item from `dead` to the queue.
             */
            requeue_count: number;
            /**
             * Format: int32
             * @description Failed delivery attempts so far. Reaching `max_retry_count` retires the Item as `dead`.
             */
            retry_count: number;
            sender_display_name?: string | null;
            /** Format: uuid */
            sender_member_id?: string | null;
            /** Format: uuid */
            space_id: string;
            status: components["schemas"]["InboxStatus"];
            summary: string;
            /** Format: uuid */
            thread_id?: string | null;
        };
        /** @enum {string} */
        InboxKind: "direct" | "mention" | "reply" | "task_activity" | "thread_activity" | "channel_activity" | "system";
        /** @enum {string} */
        InboxPriority: "hard" | "ambient";
        /** @enum {string} */
        InboxStatus: "pending" | "assigned" | "deferred" | "handled" | "dead";
        InvitationResponse: {
            accepted_at?: string | null;
            /** Format: uuid */
            accepted_by_member_id?: string | null;
            email: string;
            expires_at: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            space_id: string;
            space_name: string;
            space_slug: string;
        };
        LifecycleAction: {
            /** @enum {string} */
            action: "suspend";
            mode: components["schemas"]["SuspendMode"];
        } | {
            /** @enum {string} */
            action: "resume";
        } | {
            /** @enum {string} */
            action: "retry";
        } | {
            /** @enum {string} */
            action: "retire";
        };
        LinkTaskThreadRequest: {
            /** Format: uuid */
            thread_id: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        LoginResponse: {
            user: components["schemas"]["UserResponse"];
        };
        /** @enum {string} */
        MemberKind: "human" | "agent";
        MemberResponse: {
            access_level: components["schemas"]["AccessLevel"];
            display_name: string;
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["MemberKind"];
            permissions: string[];
        };
        MemoryContentResponse: {
            content: string;
            path: string;
            sha256: string;
            /** Format: int64 */
            size: number;
            updated_at: string;
        };
        MemoryFileResponse: {
            path: string;
            sha256: string;
            /** Format: int64 */
            size: number;
            updated_at: string;
        };
        MessageAuthor: {
            display_name: string;
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["MemberKind"];
        };
        MessageContentResponse: {
            body_markdown: string;
            /** @enum {string} */
            type: "text";
        } | {
            channel: components["schemas"]["ActionChannelResponse"];
            /** @enum {string} */
            type: "channel_created";
        } | {
            agent: components["schemas"]["ActionAgentResponse"];
            /** @enum {string} */
            type: "agent_created";
        } | {
            body_markdown: string;
            /** @enum {string} */
            type: "system_notice";
        };
        MessagePageResponse: {
            /** Format: uuid */
            channel_id: string;
            has_more_after: boolean;
            has_more_before: boolean;
            messages: components["schemas"]["MessageResponse"][];
            /** Format: int64 */
            snapshot_channel_seq: number;
        };
        /** @enum {string} */
        MessagePlacement: "root" | "reply";
        MessageResponse: {
            attachments: components["schemas"]["AttachmentResponse"][];
            attention_failures: components["schemas"]["AttentionFailureResponse"][];
            author: components["schemas"]["MessageAuthor"];
            /** Format: uuid */
            channel_id: string;
            content: components["schemas"]["MessageContentResponse"];
            created_at: string;
            deleted_at?: string | null;
            edited_at?: string | null;
            /** Format: uuid */
            id: string;
            mention_all: boolean;
            mentions: string[];
            placement: components["schemas"]["MessagePlacement"];
            /** Format: int64 */
            reply_count: number;
            /** Format: int64 */
            seq: number;
            task?: null | components["schemas"]["MessageTaskSummary"];
            task_refs: components["schemas"]["MessageTaskRefResponse"][];
            /** Format: uuid */
            thread_id: string;
        };
        MessageTaskRefResponse: {
            /** Format: int64 */
            seq: number;
            status: components["schemas"]["TaskStatus"];
            /** Format: uuid */
            task_id: string;
            title: string;
        };
        MessageTaskSummary: {
            /** Format: uuid */
            assignee_agent_member_id?: string | null;
            assignee_name?: string | null;
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            seq: number;
            status: components["schemas"]["TaskStatus"];
            title: string;
            working_elsewhere: boolean;
        };
        PairingDetailsResponse: {
            daemon_version: string;
            expires_at: string;
            hostname: string;
            os: string;
            /** Format: uuid */
            pairing_id: string;
            status: components["schemas"]["PairingStatus"];
            token_fingerprint: string;
        };
        /** @enum {string} */
        PairingStatus: "pending" | "confirmed" | "expired";
        /** @enum {string} */
        ProvisionStatus: "provisioning" | "ready" | "error";
        ReadMemoryRequest: {
            path: string;
        };
        RegisterRequest: {
            display_name: string;
            email: string;
            password: string;
        };
        RegisterResponse: {
            next: string;
            user: components["schemas"]["UserResponse"];
        };
        /** @enum {string} */
        RunOutcome: "completed" | "yielded" | "failed" | "canceled";
        RunResponse: {
            /** Format: uuid */
            agent_member_id: string;
            agent_name: string;
            continuation_note?: string | null;
            error_code?: string | null;
            finished_at?: string | null;
            focus: components["schemas"]["ThreadReferenceResponse"];
            /** Format: uuid */
            id: string;
            outcome?: null | components["schemas"]["RunOutcome"];
            started_at?: string | null;
            status: components["schemas"]["RunStatus"];
            /** Format: uuid */
            task_id?: string | null;
        };
        /** @enum {string} */
        RunStatus: "dispatched" | "working" | "completed" | "yielded" | "failed" | "canceled";
        SessionContinuityResponse: {
            /** Format: int64 */
            generation?: number | null;
            reason_code?: string | null;
            state: components["schemas"]["SessionContinuityState"];
        };
        /** @enum {string} */
        SessionContinuityState: "warm" | "cold" | "reset_required" | "unavailable";
        SpaceResponse: {
            accent: string;
            /** Format: uuid */
            current_member_id: string;
            /** Format: uuid */
            general_channel_id: string;
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            owner_member_id: string;
            slug: string;
        };
        /** @enum {string} */
        SuspendMode: "stop_after_current" | "cancel_now";
        TaskResponse: {
            /** Format: uuid */
            assignee_agent_member_id?: string | null;
            assignee_name?: string | null;
            close_reason_code?: null | components["schemas"]["CloseReason"];
            close_reason_note?: string | null;
            created_at: string;
            /** Format: uuid */
            creator_member_id: string;
            creator_name: string;
            current_run?: null | components["schemas"]["RunResponse"];
            finished_at?: string | null;
            /** Format: uuid */
            id: string;
            recent_runs: components["schemas"]["RunResponse"][];
            related_threads: components["schemas"]["ThreadReferenceResponse"][];
            result_message?: null | components["schemas"]["MessageResponse"];
            runtime_issue_code?: string | null;
            /** Format: int64 */
            seq: number;
            session_continuity: components["schemas"]["SessionContinuityResponse"];
            source_thread: components["schemas"]["ThreadReferenceResponse"];
            /** Format: uuid */
            space_id: string;
            status: components["schemas"]["TaskStatus"];
            title: string;
            updated_at: string;
        };
        /** @enum {string} */
        TaskStatus: "todo" | "in_progress" | "in_review" | "done" | "closed";
        ThreadReadResponse: {
            /** Format: uuid */
            channel_id: string;
            is_following: boolean;
            replies: components["schemas"]["MessageResponse"][];
            root: components["schemas"]["MessageResponse"];
            /** Format: int64 */
            snapshot_channel_seq: number;
            task?: null | components["schemas"]["MessageTaskSummary"];
            task_relation?: null | components["schemas"]["ThreadRelation"];
            /** Format: uuid */
            thread_id: string;
        };
        ThreadReferenceResponse: {
            /** Format: uuid */
            channel_id: string;
            channel_slug?: string | null;
            /** Format: uuid */
            id: string;
            relation: components["schemas"]["ThreadRelation"];
            /** Format: uuid */
            root_message_id: string;
            /** Format: int64 */
            root_message_seq: number;
        };
        /** @enum {string} */
        ThreadRelation: "source" | "related";
        ThreadSubscriptionResponse: {
            /** Format: uuid */
            channel_id: string;
            is_following: boolean;
            /** Format: uuid */
            thread_id: string;
        };
        UpdateAgentRequest: {
            lifecycle?: null | components["schemas"]["LifecycleAction"];
            role_text?: string | null;
        };
        UpdateMemberRequest: {
            access_level?: null | components["schemas"]["AccessLevel"];
            permissions?: string[] | null;
        };
        UpdateMessageRequest: {
            body_markdown: string;
            mention_all: boolean;
            mentions: string[];
        };
        UpdateTaskRequest: {
            /** Format: uuid */
            assignee_agent_member_id?: string | null;
            title?: string | null;
        };
        UserResponse: {
            display_name: string;
            email: string;
            /** Format: uuid */
            id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;

export type AddChannelAgentsInput = components["schemas"]["AddChannelAgentsRequest"];
export type Agent = components["schemas"]["AgentResponse"];
export type AgentRuntime = components["schemas"]["AgentRuntimeResponse"];
export type AgentMemoryContent = components["schemas"]["MemoryContentResponse"];
export type AgentMemoryFile = components["schemas"]["MemoryFileResponse"];
export type Attachment = components["schemas"]["AttachmentResponse"];
export type AttentionConfig = components["schemas"]["AttentionConfig"];
export type Channel = components["schemas"]["ChannelResponse"];
export type ChannelList = components["schemas"]["ChannelListResponse"];
export type ChannelMembers = components["schemas"]["ChannelMembersResponse"];
export type CompleteUploadInput = components["schemas"]["CompleteUploadRequest"];
export type Computer = components["schemas"]["ComputerResponse"];
export type ConfirmPairingInput = components["schemas"]["ConfirmPairingRequest"];
export type CreateAgentInput = components["schemas"]["CreateAgentRequest"];
export type CreateChannelInput = components["schemas"]["CreateChannelRequest"];
export type CreateDirectMessageInput = components["schemas"]["CreateDirectMessageRequest"];
export type CreateInvitationInput = components["schemas"]["CreateInvitationRequest"];
export type CreateMessageInput = components["schemas"]["CreateMessageRequest"];
export type CreateSpaceInput = components["schemas"]["CreateSpaceRequest"];
export type CreateTaskInput = components["schemas"]["CreateTaskRequest"];
export type CreateThreadReplyInput = components["schemas"]["CreateThreadMessageRequest"];
export type CreateUploadInput = components["schemas"]["CreateUploadRequest"];
export type DirectMessage = components["schemas"]["DirectMessageResponse"];
export type ErrorEnvelope = components["schemas"]["ErrorEnvelope"];
export type InboxItem = components["schemas"]["InboxItemResponse"];
export type Invitation = components["schemas"]["InvitationResponse"];
export type CreatedInvitation = components["schemas"]["CreatedInvitationResponse"];
export type LoginInput = components["schemas"]["LoginRequest"];
export type LoginResponse = components["schemas"]["LoginResponse"];
export type Member = components["schemas"]["MemberResponse"];
export type Message = components["schemas"]["MessageResponse"];
export type MessageAuthor = components["schemas"]["MessageAuthor"];
export type MessagePage = components["schemas"]["MessagePageResponse"];
export type MessageTaskRef = components["schemas"]["MessageTaskRefResponse"];
export type MessageTaskSummary = components["schemas"]["MessageTaskSummary"];
export type PairingDetails = components["schemas"]["PairingDetailsResponse"];
export type ReadAgentMemoryInput = components["schemas"]["ReadMemoryRequest"];
export type RegisterInput = components["schemas"]["RegisterRequest"];
export type RegisterResponse = components["schemas"]["RegisterResponse"];
export type Space = components["schemas"]["SpaceResponse"];
export type Task = components["schemas"]["TaskResponse"];
export type TaskStatus = components["schemas"]["TaskStatus"];
export type Run = components["schemas"]["RunResponse"];
export type RunStatus = components["schemas"]["RunStatus"];
export type SessionContinuity = components["schemas"]["SessionContinuityResponse"];
export type ThreadReference = components["schemas"]["ThreadReferenceResponse"];
export type ThreadRead = components["schemas"]["ThreadReadResponse"];
export type ThreadSubscription = components["schemas"]["ThreadSubscriptionResponse"];
export type UpdateAgentInput = components["schemas"]["UpdateAgentRequest"];
export type UpdateTaskInput = components["schemas"]["UpdateTaskRequest"];
export type LinkTaskThreadInput = components["schemas"]["LinkTaskThreadRequest"];
export type CompleteTaskInput = components["schemas"]["CompleteTaskRequest"];
export type CloseTaskInput = components["schemas"]["CloseTaskRequest"];
export type UpdateMemberInput = components["schemas"]["UpdateMemberRequest"];
export type User = components["schemas"]["UserResponse"];
