/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: "var(--bg)",
        panel: "var(--panel)",
        "panel-2": "var(--panel-2)",
        "panel-3": "var(--panel-3)",
        "panel-event": "var(--panel-event)",
        border: "var(--border)",
        "border-soft": "var(--border-soft)",
        "border-event": "var(--border-event)",
        "border-strong": "var(--border-strong)",
        text: "var(--text)",
        "text-muted": "var(--text-muted)",
        "text-faint": "var(--text-faint)",
        "text-whisper": "var(--text-whisper)",
        accent: "var(--accent)",
        "accent-bg": "var(--accent-bg)",
        "accent-border": "var(--accent-border)",
        action: "var(--action)",
        "action-bg": "var(--action-bg)",
        agent: "var(--agent)",
        "agent-bg": "var(--agent-bg)",
        "agent-border": "var(--agent-border)",
        running: "var(--running)",
        "running-bg": "var(--running-bg)",
        "running-border": "var(--running-border)",
        mention: "var(--mention)",
        "mention-bg": "var(--mention-bg)",
        "mention-border": "var(--mention-border)",
        tool: "var(--tool)",
        "tool-bg": "var(--tool-bg)",
        "tool-border": "var(--tool-border)",
        error: "var(--error)",
        "error-bg": "var(--error-bg)",
        "error-border": "var(--error-border)",
        done: "var(--done)",
        reasoning: "var(--reasoning)",
      },
      borderRadius: {
        sm: "0px",
        md: "2px",
        lg: "4px",
      },
      borderWidth: {
        hard: "2px",
      },
      boxShadow: {
        hard: "3px 3px 0 0 var(--border)",
        card: "2px 2px 0 0 var(--border)",
      },
      fontFamily: {
        ui: 'var(--font-ui)',
        display: 'var(--font-display)',
        body: 'var(--font-body)',
        mono: 'var(--font-mono)',
      },
    },
  },
  plugins: [],
};
